tickers:
- TCGL
- FATBB
- TWNP
- MOVE
- BNAI
- DRCT
- SPAI
- PCSA
- MWYN
- LSH
- BITF
- BE
- SOXL
- PLUG
- W
- AMC
- BSX
- HUT
- AMD
- MGM
- WULF
- EBAY
- PLTR
- U
- BLNK
- FIG
- MVIS
- HIVE
- MU
- CLSK
- AMAT
- MARA
- RIOT
- VST
- HOOD
- UBER
- XRP-USD
- INFY.NS
- DOGE-USD
- ADA-USD
- TLN
- CEG
- ETSY
- WKHS
- SOL-USD
- EVGO
- INTU
- TROW
- BB
- TCS.NS
- LLY
- SAN
- PRU
- SNOW
- ETH-USD
- NET
- KKR
- CZR
- AVGO
- COIN
- NVDA
- META
- AMZN
- GOOGL
- NFLX
- MSTR
- RELIANCE.NS
- HDFCBANK.NS
- ICICIBANK.NS
- TATAMOTORS.NS
